/** The fragments the SDK actually calls. Full ABI lives in contracts/out. */
export const SLA_ESCROW_ABI = [
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "buyerBalance",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "sellerBalance",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "consumed",
    stateMutability: "view",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "endpoints",
    stateMutability: "view",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [
      { name: "seller", type: "address" },
      { name: "price", type: "uint128" },
      { name: "maxLatencyMs", type: "uint32" },
      { name: "expectedStatus", type: "uint16" },
      { name: "schemaHash", type: "bytes32" },
      { name: "challengeWindow", type: "uint64" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "registerEndpoint",
    stateMutability: "nonpayable",
    inputs: [
      { name: "price", type: "uint128" },
      { name: "maxLatencyMs", type: "uint32" },
      { name: "expectedStatus", type: "uint16" },
      { name: "schemaHash", type: "bytes32" },
      { name: "challengeWindow", type: "uint64" },
      { name: "bondAmount", type: "uint256" },
    ],
    outputs: [{ name: "endpointId", type: "bytes32" }],
  },
  {
    type: "function",
    name: "redeemWithAck",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "auth",
        type: "tuple",
        components: [
          { name: "buyer", type: "address" },
          { name: "endpointId", type: "bytes32" },
          { name: "requestId", type: "bytes32" },
          { name: "amount", type: "uint128" },
          { name: "requestedAtMs", type: "uint64" },
          { name: "deadline", type: "uint64" },
        ],
      },
      { name: "authSig", type: "bytes" },
      {
        name: "receipt",
        type: "tuple",
        components: [
          { name: "requestId", type: "bytes32" },
          { name: "statusCode", type: "uint16" },
          { name: "servedAtMs", type: "uint64" },
          { name: "bodyHash", type: "bytes32" },
        ],
      },
      { name: "receiptSig", type: "bytes" },
      { name: "ackSig", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "batchRedeemWithAck",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "auths",
        type: "tuple[]",
        components: [
          { name: "buyer", type: "address" },
          { name: "endpointId", type: "bytes32" },
          { name: "requestId", type: "bytes32" },
          { name: "amount", type: "uint128" },
          { name: "requestedAtMs", type: "uint64" },
          { name: "deadline", type: "uint64" },
        ],
      },
      { name: "authSigs", type: "bytes[]" },
      {
        name: "receipts",
        type: "tuple[]",
        components: [
          { name: "requestId", type: "bytes32" },
          { name: "statusCode", type: "uint16" },
          { name: "servedAtMs", type: "uint64" },
          { name: "bodyHash", type: "bytes32" },
        ],
      },
      { name: "receiptSigs", type: "bytes[]" },
      { name: "ackSigs", type: "bytes[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawSeller",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "event",
    name: "Settled",
    inputs: [
      { name: "requestId", type: "bytes32", indexed: true },
      { name: "endpointId", type: "bytes32", indexed: true },
      { name: "buyer", type: "address", indexed: true },
      { name: "amount", type: "uint128", indexed: false },
      { name: "latencyMs", type: "uint32", indexed: false },
      { name: "fastPath", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EndpointRegistered",
    inputs: [
      { name: "endpointId", type: "bytes32", indexed: true },
      { name: "seller", type: "address", indexed: true },
      { name: "price", type: "uint128", indexed: false },
      { name: "maxLatencyMs", type: "uint32", indexed: false },
      { name: "expectedStatus", type: "uint16", indexed: false },
      { name: "schemaHash", type: "bytes32", indexed: false },
      { name: "challengeWindow", type: "uint64", indexed: false },
    ],
  },
] as const;

export const ERC20_ABI = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
] as const;
